### ISSUE TITLE
3 simple fixes

### ISSUE THREAD

**Issue by ahingliu** [Rlam1217/Instanews-App#2]
Hi Richard, as per Anvit instruction, please consider the following changes:

Issue 1:
There is an extra .css file totally commented that can be deleted to make your project cleaner.

Issue 2:
@ the parcial “_typography” you have all more fonts that you need. If you’re using only open_sanslight, the rest is redundant.

Issue 3: 
@ main.js, line 36 added open the link to a new tab.

**Comment by Rlam1217** [comment]
Thanks fixed
